### ISSUE TITLE
TensorFlow version for MNIST?

### ISSUE THREAD

**Issue by florinmatei** [xiaojiew1/KDGAN#2]
What TensorfFlow version is needed to run the MNIST example? Thank you!

**Comment by florinmatei** [comment]
I think the error below is due to TensorFlow version mismatch:

Traceback (most recent call last):
  File "pretrain_gen.py", line 28, in <module>
    tn_gen = GEN(flags, mnist.train, is_training=True)
  File "/Users/florinmatei/Projects/KDGAN2/KDGAN/mdlcompr/gen_model.py", line 39, in __init__
    self.gumbel_labels = gumbel_softmax(self.logits, self.gumbel_temperature)
  File "/Users/florinmatei/Projects/KDGAN2/KDGAN/mdlcompr/gumbel_softmax.py", line 11, in gumbel_softmax
    y = logits + sample_gumbel(tf.shape(logits))
AttributeError: 'Session' object has no attribute 'shape'
